version = 0.1

[default]
[default.global]
stack_name = "family-cat-photos"

[default.deploy]
[default.deploy.parameters]
resolve_s3 = true
capabilities = ["CAPABILITY_IAM"]
confirm_changeset = true
fail_on_empty_changeset = true
s3_prefix = "family-cat-photos"

[default.build.parameters]
use_container = false

