version = 0.1

[default]
[default.global]
stack_name = "family-cat-photos"

[default.global.parameters]
region = "us-east-1"

[default.deploy]
[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM"]
confirm_changeset = true
fail_on_empty_changeset = true
s3_bucket = "family-cat-photos-artifacts-837132623653"
s3_prefix = "family-cat-photos"

[default.build.parameters]
use_container = false
